### ISSUE TITLE
Manually naming duplicate reports

### ISSUE THREAD

**Issue by eatorange** [worldbank/ietoolkit#10]
Is there a way to manually name the file of duplicate reports? Suppose we use “ieduplicates” command for many different dataset, then we need to save each report separately.

**Comment by kbjarkefur** [comment]
Thanks you for your suggestion @eatorange ! Would it be sufficient with having a suffix that change? For example, say that you have a option called filesuffix() and for data set AAA you say filesuffix("AAA") and then the report will be given the name iedupreport_AAA. Then for data set BBB you say filesuffix("BBB") and the file name will be iedupreport_BBB. Without using the filesuffix() option the name will be iedupreport, just like now.

I think this would provide the flexibility that you are asking for, but still maintain a structure and standard across projects. 

Let me know what you think!
