### ISSUE TITLE
iebaltab: tweaks in t-test?

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/ietoolkit#109]
about [this](http://blogs.worldbank.org/impactevaluations/comment/4598#comment-4598) comments discussion, should we 
1. make t-tests display optional?
2. make it optional to display the normalized difference?

**Comment by bbdaniels** [comment]
Here's the [relevant Statalist thread](https://www.statalist.org/forums/forum/general-stata-discussion/general/724594-include-normdiff-in-summary-statistic-table-using-esttab) and one of several [citations](http://www.nber.org/WNE/lect_1_match_fig.pdf):

![screenshot 2017-11-27 10 26 59](https://user-images.githubusercontent.com/1459122/33274262-91d22cf0-d35d-11e7-816d-d6898d1410cc.png)

**Comment by luizaandrade** [comment]
This is now published in SSC.
