### ISSUE TITLE
iematch : add cap on how many matches in m-1 matches

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/ietoolkit#112]

**Comment by kbjarkefur** [comment]
Need modification to algorithm to implement. Previously **m1** matches did not use an algorithm as it was possible to solve in one iteration. If there is no maximum number of matches in an **m1** match then all base obs are match to the target obs they prefer (as long as it is within maxdiff() if that option is used).

In a one-to-one match a match is done if a pair of base and target obs mutually prefer each other among all unmatched observations. That is repeated until all base obs are matched (or if **maxdiff()** is used until base observations are either matched or have no more unmatched target obs within the **maxdiff()**). 

If a maximum number of matches in a many-to-one match is used, then we will have to update the step that finds preferred matches so that a target obs get as many preferred matches among unmatched base obs as the maximum number of matches set. Then a base obs is matched if it is among the set of mutually preferred obs of the target obs.

**Comment by kbjarkefur** [comment]
Needs more testing but I think I have solved this. 

The trick was to match one base observation to a target observation at the time and use the one-to-one match algorithm but with the only difference that the target obs is still kept eligible for further matches until the maximum number of counts are reached. The simplest option is usually the solution but I did not see this option immediately.

**Comment by kbjarkefur** [comment]
Close issue when version with this solution is published on SSC

**Comment by luizaandrade** [comment]
This is now published in SSC.

**Comment by luizaandrade** [comment]
This is now published in SSC.
