### ISSUE TITLE
iegitaddmd : allow user to use their own placeholder file

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/ietoolkit#118]
I guess it would benefit a wider uptake if other organizations are allowed to use a file from disk as placeholder file instead of the file this command is creating. And individual teams within DIME might also prefer to write their own README file.

This is quite quick and I can do this myself, just wanted to post an issue so that I don't forget.

**Comment by kbjarkefur** [comment]
Solution in PR #119, remove _resolved_ label if the PR is rejected. Close the issue when update is on SSC if PR is merged.

**Comment by eatorange** [comment]
I just used the latest version of the command on the server, and it seems it just replaces all Readme.md files even if there are already "Readme.md" file, so I had to discard changes for the directories which already had "Readme.file" my team wrote.

I went through this issue and  #119 , and it seems if it is updated, the command will display an error message when neither "replace" nor "skip" option is specified? If yes, then I might be able to use this command more safely.

**Comment by eatorange** [comment]
Oh sorry I knew that it was NOT published yet. I meant "when it is updated laster". Sorry for not clearly stating it.

I tested the version in the branch `issue-118` and it worked. Also, I made a mistake when I was testing the version in the master branch (the one in the SSC) - it works as if "skip" is specified. Sorry for confusing!

**Comment by luizaandrade** [comment]
This is now published in SSC.
