### ISSUE TITLE
iebaltab: display F-test for joint equality instead of pairwise t-test for equality in means

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/ietoolkit#121]
Displaying pairwise t-test is an issue when there are different treatment arms. In this case, it might be useful to regress the variables in the table by dummies for the different treatment arms and using and F-test to check if their coefficients are all equal.

**Comment by kbjarkefur** [comment]
Would that be an addition to the current table layout or a completely alternative layout? I think the latter as I do not know how they would fit in to the current table layout. Unless you only used this issue as a reminder for yourself and just want to go ahead and do this yourself at some later point, maybe it would be a good idea to paste an example from Google or to type up a mock table in LaTeX so we know that we are envisioning the same thing.

**Comment by luizaandrade** [comment]
That would be a different layout, with the F-test in each line instead of the T-test. My idea is making what is currently the t-test part of the table optional, and then the user can choose to display the t-test (pairwise or compared to control as now), the normalized difference or the F-test.

**Comment by luizaandrade** [comment]
Reference for this: http://blogs.worldbank.org/impactevaluations/tools-trade-joint-test-orthogonality-when-testing-balance

**Comment by kbjarkefur** [comment]
After we published this up date we should ask David if it is ok if we make a comment to that blog post with a link to ietoolkit. I am sure more people link to that blog post for reference.

**Comment by luizaandrade** [comment]
This is now published in SSC.
