### ISSUE TITLE
DIME wiki link

### ISSUE THREAD

**Issue by stevenglover** [worldbank/ietoolkit#139]
Link to the DIME wiki in the ietoolkit stata help file does not lead to the ietoolkit page on the wiki
Link is: https://dimewiki.worldbank.org/wiki/Ietoolkit , should probably go to: https://dimewiki.worldbank.org/wiki/Stata_Coding_Practices#ietoolkit

**Comment by kbjarkefur** [comment]
Thanks @stevenglover ! I will fix and include in next version!

**Comment by mariaruth** [comment]
In the meantime i created a redirect page for that link on the wiki

**Comment by kbjarkefur** [comment]
Good idea! Thanks @mariaruth !

**Comment by kbjarkefur** [comment]
This issue is now fixed but will only be included in next version of ietoolkit. We will keep this issue open until a version including this fix is released on SSC.
