### ISSUE TITLE
iefolder : location for GIS files

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/ietoolkit#140]
Based on question in Stata map lab right now

Should we have a designated folder for this? When does these files include private information and when does it? It is only one of them?

**Comment by bbdaniels** [comment]
Maybe? I usually end up creating "GIS" and "Metadata" alongside the Final and Intermediate folders. One possibility would be to have an option that takes any additional folder names, ie `moredata("GIS" "Metadata" [...])`

**Comment by kbjarkefur** [comment]
I just overheard that in a question to you and figured I should log it. 

My thinking when developing `iefolder` was always that some project specific folders will always have to be created. It is confusing if we add too many specific folders and most of them ending up unused.

The argument for would be if there is some best practice that we would push people towards. As in remember to put the raw in the encrypted branch etc.

Let's see if anyone else has an opinion before we make a decision on whether or not to implement it.

**Comment by kbjarkefur** [comment]
@luizaandrade and I just decided to not do this. It is too specific. `iefolder` have to create so many specific folders if we would include this as well.
