### ISSUE TITLE
iefolder: add "/Raw/" folder to /DataSets/

### ISSUE THREAD

**Issue by bbdaniels** [worldbank/ietoolkit#145]
One option for the first cleaning pass is to create an identical non-PII version of the encrypted data, and put this in a /Raw/ folder (not Intermediate or Final). It might be reasonable to provide by default and is relatively easy to do.

**Comment by luizaandrade** [comment]
As Kris said in issue #140, the point of iefolder is to push people toward best practices, and if there's a Raw folder in the non-encrypted folder, it's easier to miss the one in the encrypted folder.

I think adding a folder called something like "Raw de-identified data" folder to DataSets would be useful. Even though it's easy to customize the folder structure for project-specific demands, I think most projects would use such a folder.

I also think this idea probably came up when the command was created and there's a good reason why it is not there, so let's wait for Kris before we make a decision on this.

**Comment by bbdaniels** [comment]
Yes, de-identified is exactly what I meant here and that is a good point to emphasize. Would love to hear Kris' thoughts.

**Comment by kbjarkefur** [comment]
I like this with Luiza's addition of calling it **deidentified**. I like one word folder names as spaces can cause problems, and special characters apart from underscores should be avoided in file or folder names. And I think we should not include the word raw as it would make invite people to put raw data there. This is fairly easy to implement and does not have any backward compatibility issues, so I will assign this to myself and implement at some point. Thanks!

**Comment by bbdaniels** [comment]
I think that's perfect!

**Comment by kbjarkefur** [comment]
Issue will be closed when published on SSC

**Comment by kbjarkefur** [comment]
DIME Wiki updated to reflect this change in best practice.

https://dimewiki.worldbank.org/wiki/DataWork_Survey_Round#DataSets_Folder
