### ISSUE TITLE
ieduplicates: notes variable name

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/ietoolkit#152]
The notes exported by ieduplicates are saved under the name "notes". If the data set already contained a variable with that name, it can create problems.

**Comment by kbjarkefur** [comment]
I think my thinking was that there was two options. Taking a risk for a name change, or having names difficult to work with. 

I guess one middle ground would be to have an option called `customvarnames(notes=dup_note, correct=notToModify)` etc. Then it is up to the user to set the names. Would that be a solution?

**Comment by kbjarkefur** [comment]
What do you think of this solution @luizaandrade and @MRuzzante? Would it be satisfactory to you?

**Comment by MRuzzante** [comment]
Yes! I would definitely allow the user to customize the name of the columns. 

Also, in order to make him/her aware of this, I would add a warning reporting this when the issue arises (something like: _the `varlist` specified in `keepvar` contains a variable called `notes` which potentially conflicts with one column of the duplicates report. If you would like to distinguish it in a separate column, you can use the option `custovarnames`._)

**Comment by kbjarkefur** [comment]
Did you run into this error and did not get an error? I think you do get an error, but you are right, if we implement this option we should notify the user of this command in the error message and maybe that is the point you are making...

**Comment by MRuzzante** [comment]
I just checked it with some sample data and it gives that error:
> variable **notes** already defined

But, I am pretty sure that when we ran it last time, we didn't get any error: we just saw that the notes column in the duplicate report was filled with the enumerator notes (as the name of that variable was not previously changed).

So, I guess the best solution would be to change this error to something more explanatory and, then, add an option for renaming inside `ieduplicates` without the need of doing it before running it.

**Comment by kbjarkefur** [comment]
Temporary fix in commit b5903f5 to be included in v5.6. This fix provide a better error message and solution. The final fix will be when the names used in the excel report can be set by the user. That will be included in a later version of **ietoolkit**.

**Comment by kbjarkefur** [comment]
@SaoriIwa , this might be a good fit for you. I did the first part and then you can do the second part of making the variable names possible to set by the user. - Let's do what we discussed for `ietestform` first, but then you could do this. Make sure to discuss this with me first.

**Comment by SaoriIwa** [comment]
@kbjarkefur Sounds good, I will take a look after `ietestform` and will check in with you to start.

**Comment by kbjarkefur** [comment]
This command was moved to [iefieldkit](https://github.com/worldbank/iefieldkit) and the discussion regarding this issue will be continued in that repo.
