### ISSUE TITLE
ieddtab : issues from test session

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/ietoolkit#158]
Write comments here

**Comment by kbjarkefur** [comment]
row title breaks if varname is shorter then the title "Varaible" for that column

**Comment by kbjarkefur** [comment]
Spell out coefficient in table header

**Comment by kbjarkefur** [comment]
in windows output trailing zeros are dropped so decimals are not lined up

**Comment by kbjarkefur** [comment]
no option for clustering

**Comment by MRuzzante** [comment]
- [ ]  When running `ieddtab varlist t, t(t) tmt(tmt)` or `ieddtab death tmt, t(t) tmt(tmt)` put an error such as "`t` is already used as time variable". This might happens when the treatment or time variables are called by using a shortcut with *.

- [ ] `ieddtab stringVar, t(t) tmt(tmt)`: put error "varlist contains string variables"
- [ ] `ieddtab factorVar, t(t) tmt(tmt)`: put error "varlist contains factor variable"

- [ ] `ieddtab varlist, t(t) tmt(tmt) covar(region)`: add warning on string/factor variables in covariates as above to warn the user

**Comment by kbjarkefur** [comment]
check that all outcome vars are numeric and return sensible error message

**Comment by morevba** [comment]
Should allow for multiple treatment arms (i.e 0 = no treatment, 1 = cash, 2 = food)

**Comment by sakina0320** [comment]
The tex output file is pringting \end{document} at the very end, when the stata command specifies to create a non stand-alone tex table. Please remove this line.

**Comment by kbjarkefur** [comment]
Typo on texnotewidth option in help file: "entre"

**Comment by kbjarkefur** [comment]
make option t to time with abbreviation t
treatment but abbreviate to treat

**Comment by kbjarkefur** [comment]
**Do before first public version**
- [ ] make option t to time with abbreviation t @kbjarkefur 
- [ ] treatment but abbreviate to treat @kbjarkefur 
- [ ] Write "Coef." instead of Coef in header @kbjarkefur 
- [ ] Option for clustering, bootstrap and all the other vce options @luizaandrade 
- [ ] make sure time or treat var is not also outcome var @kbjarkefur 
- [ ] test that all outcome var are numeric @kbjarkefur 
- [ ] The tex output file is printing \end{adjustbox}, \end{table} and \end{document @luizaandrade 
- [ ] Typo on texnotewidth option in help file: "entre" @luizaandrade 
- [ ] allow if/in @kbjarkefur 
- [ ] return the result matrix @kbjarkefur 
- [ ] change diformat to format @kbjarkefur 
- [ ] change to nonote and addnote @luizaandrade

 **Do Later**
- [ ] row title breaks if varname is shorter then the title "Varaible" for that column -- not urgent as stats are still there and works in tex  @kbjarkefur 
- [ ] in windows output trailing zeros are dropped so decimals are not lined up -- not urgent as stats are still there and works in tex @kbjarkefur 

**Discuss Later**
* Should allow for multiple treatment arms (i.e 0 = no treatment, 1 = cash, 2 = food) -- Maybe maybe but not unless there is a big demand

**Wont fix**
* ieddtab factorVar, t(t) tmt(tmt): put error "varlist contains factor variable" -- Stata error is good enough

**Comment by kbjarkefur** [comment]
All issues mentioned in this thread is either fixed or have been opened in dedicated issues. Thank you @MRuzzante , @morevba , @sakina0320 , @bbdaniels (and everyone else who participated but did not comment here) so much for your help in testing and giving feedback!

This issue will be closed once the command is on SSC
