### ISSUE TITLE
ieddtab : add an option to not show stars in table

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/ietoolkit#165]
@luizaandrade , I can do all work apart from the tex implementation. I will let you know when I have done that.

**Comment by kbjarkefur** [comment]
@luizaandrade , I will call this option `stardrop` to keep is as similar as possible to how the corresponding command is specified in **estout**. See `help estout##stardrop`. **estout** allows a _varlist_ so that this is only applied to some of the variables. I do not know if I like that, so I will not allow that stars are suppressed for just some of the variables, unless you think differently.

**Comment by luizaandrade** [comment]
Agreed.

**Comment by luizaandrade** [comment]
This is tested and working. The branch has been merged to develop. This issue will be closed once the updates are up on SSC.
