### ISSUE TITLE
ieduplicates : unique uniquevar listed as having duplicates

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/ietoolkit#188]
Reported in person by @luizaandrade and @MRuzzante .

The error message is that the variable key (the uniquevar) does not uniquely identify the data set when merging the report back to the original data set.

**Comment by kbjarkefur** [comment]
The problem was that when the report was imported to Stata, somehow it imported some Excel rows as empty rows. These empty rows all had the same value for *key*, i.e. empty, and was therefore not considered uniquely identifying the data.

This is fixed by deleting all empty rows immediately after importing the report.

**Comment by MRuzzante** [comment]
Yes. the code is working now! 🥇

**Comment by kbjarkefur** [comment]
Thanks for reporting and testing @MRuzzante !

This is merged to the `develop` branch and this issue will be closed once this update is on released on SSC.

**Comment by luizaandrade** [comment]
`iefieldkit` is up! Closing this issue.
