### ISSUE TITLE
iebaltab : in latex underscores in variable names are interpreted as subscript

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/ietoolkit#21]
If a variable name is used as row title and that variable name includes and underscore, for example d_harverst, then the "h" will be subscripted to the "D". 

They way to get around that now is variable a variable label and use option rowvarlabel, or to give it another label using the rwolabel() option. But if there is an easy way to include an escape character before the underscore, then that would be great.

**Comment by luizaandrade** [comment]
That's pretty easy to fix. The escape character is "\", so we'd only have to replace "_" for "\_"

**Comment by kbjarkefur** [comment]
That's great! And thanks for volunteering! :+1:  When your work schedule allows, branch and push the fix to the develop branch!

**Comment by luizaandrade** [comment]
Issue fixed and pull request sent to develop branch!

**Comment by kbjarkefur** [comment]
Thank you @luizaandrade ! Pull request is merged!

I will close this issue as soon as the update is sent to SSC.

Thanks!
