### ISSUE TITLE
iefolder master do-files 

### ISSUE THREAD

**Issue by morevba** [worldbank/ietoolkit#212]
This is a minor issue but it would be great if at the end of each of the master do-files created by iefolder there was a line at the end that read "****** End of do-file *****" so new users know when all the globals and commands are done. I know this is low priority so no rush, it's just something that I noticed recently.

**Comment by luizaandrade** [comment]
Thanks for the suggestion, @morevba! Is that something you'd be interested in implementing? If so, feel free to send a PR. otherwise.

**Comment by kbjarkefur** [comment]
I spoke to @morevba about this. While the practice of adding `****** End of do-file *****` at the end of a do-file is not a bad practice as it tells the users to not write code below this line, we will not implement this as if a team does not know to follow this pracice, they might write their own code at the bottom of the file, and then the `****** End of do-file *****` is no longer the end of the code.

So in teams where it is not enforced to not write below this line, it might be confusing to have this, so we will not push this on all projects.
