### ISSUE TITLE
[iegitaddmd] - no README in .git folder

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/ietoolkit#229]
`iegitadd`  should ignore `.git` folder.

Putput submitted by @bbdaniels :
```
You are about to create a file [README.md] in the folder [/Users/username/GitHub/eq-kids/.git/objects/info].
```

**Comment by bbdaniels** [comment]
Easiest is to ignore any invisible folder I think? On MacOS this is done just by skipping any folder whose name starts with `.`

**Comment by kbjarkefur** [comment]
`.git` folder should be ignored by default, that is straightforward.

I think it is too broad to ignore all folders starting on `.` as default. But it would be great feaster. 

I am thinking an `skipfolder()` option where you list folder names to be ignored. `.git` is the only default value.

What do you think?

**Comment by bbdaniels** [comment]
That's a good idea, is it possible to make it work with wildcards so I can do like `skip(.*)` etc?

**Comment by kbjarkefur** [comment]
Possible, yes. Worth implementing for this fix, not sure. 

It can be put on the wish list as a utility function. And once we have that we can apply it here too. But for now I will probably implement without wildcards.

**Comment by kbjarkefur** [comment]
Suggested solution in #230
