### ISSUE TITLE
[iebaltab]: show one "number of observations" at the bottom of table in .tex output

### ISSUE THREAD

**Issue by mizuhirosuzuki** [worldbank/ietoolkit#242]
When the numbers of observations are the same for all variables, it might be nice to have one N at the bottom of the table for each group (control and treatment).
For now we have numbers of observations for each variable in each group, which makes it a bit hard to compare numbers across groups.
Of course this doesn't work when the numbers of observations are different across variables (eg. missing values).
The "sutex" command has a feature like this: show one N if all variables have the same N, and show different N's (as iebaltab does now) if variables have different N's.

I want the same feature for ieddtab (and maybe some of other commands too).

**Comment by mizuhirosuzuki** [comment]
Gee, I found this feature too... Never mind

**Comment by kbjarkefur** [comment]
:) Same question, could this have been made more clear?

**Comment by mizuhirosuzuki** [comment]
sorry for the confusion, but I just wanted exactly what "onerow" option does. Now I found the option so I just closed the issue.
