### ISSUE TITLE
ieboilstart : remove references to dofile in help file

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/ietoolkit#26]
In an earlier version of ieboilstart the command created a dofile used to set the settings. This is no longer the case but there this dofiel is still mentioned in the help file.

**Comment by mrimal** [comment]
Done. Included in merge #24. Thanks!

**Comment by kbjarkefur** [comment]
Great thanks! I have merged the pull request and I will close this comment when the updated file is on the SSC server.
