### ISSUE TITLE
Update `ieboilstart` with newer Stata versions

### ISSUE THREAD

**Issue by skhiggins** [worldbank/ietoolkit#263]
`ieboilstart` appears to only allow through versions 15.1 and we are now on Stata 17. From `ieboilstart.ado`:

```stata
local stata_versions "11 11.0 11.1 11.2 12 12.0 12.1 13 13.0 13.1 14 14.0 14.1 14.2 15 15.0 15.1"
```

**Comment by kbjarkefur** [comment]
Hi @skhiggins ! Thanks for pointing this out! You are right that the published version `ieboilstart` only allow through versions 15.1.  In a yet to be published version of `ietoolkit` this has been updated, but that publication is waiting for some new features we are working on in other commands. But those features have been taking such a long time now that maybe we should make a mini-publication to get a small update like this out. I will comment here when `ieboilstart` is updated.

**Comment by kbjarkefur** [comment]
@skhiggins , we have now published an update with this so the most recent versions are included in `ieboilstart`

**Comment by skhiggins** [comment]
Thanks!
