### ISSUE TITLE
iedorep review Sep 2022 - differentiation of error messages from do-files and from `iedorep`

### ISSUE THREAD

**Issue by luisesanmartin** [worldbank/ietoolkit#292]
If an input do-file produces an error, the error message is displayed normally. If the error comes from `iedorep`, the error is also shown in the same way. I think it's important that `iedorep` shows some kind of warning to differentiate when the error message originated because the input do-file didn't fully run and when it was because something caused an error in the `iedorep` execution

**Comment by bbdaniels** [comment]
Great idea. To solve this I have added a callout in d859a6ab4b7b0ddce99aaa87bf036e45a55aaf93 that reports the beginning and end of dofile runs. I can't explicitly identify anything outside that I think but it should now be clear which state the program is in. For example, you will get:

```
Entering "/Users/bbdaniels/GitHub/ietoolkit/run/iedorep/iedorep-target-1.do" run....
RUNFILE: THIS VALUE SHOULD ALWAYS BE THE NUMBER ONE: 1
SAME FROM THE SUBROUTINE: 1
SAME FROM THE SUBROUTINE: 1
RUNFILE: THIS VALUE SHOULD ALWAYS BE THE NUMBER ONE: 1
SAME FROM THE SUBROUTINE: 1
SAME FROM THE SUBROUTINE: 1
Done with "/Users/bbdaniels/GitHub/ietoolkit/run/iedorep/iedorep-target-1.do"!
```

When it runs without error, and if there is an internal error you will not get the last line. Does that work?

**Comment by luisesanmartin** [comment]
it does. Closing the issue now
