### ISSUE TITLE
`iedorep`: mismatches are not errors and make proper Stata table for output

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/ietoolkit#306]
A mismatch between two runs should not be called "error". The word "error" should be reserved for when the command did not work as expected.

Fix the table such that it is a Stata smcl table were errors can be highlighted in red. See more in this issue: https://github.com/worldbank/ietoolkit/issues/304

**Comment by kbjarkefur** [comment]
Suggested names to use instead of "error" for mismatches between runs:

* mismatch
* difference
* discrepancies 

Feel free to suggest other names

**Comment by mariaruth** [comment]
Agree with using a different term than error. I prefer 'instability' (or instabilities?)
