### ISSUE TITLE
iematch - idvar option multiple id vars

### ISSUE THREAD

**Issue by morevba** [worldbank/ietoolkit#32]
The idvar option does not allow for a varlist even though it is specified in the help file.

**Comment by kbjarkefur** [comment]
You are right, I made a change to the matching algortithm, and now it can only handle one ID var. I can fix that for next update. In general I recommend having only one ID var, but I am sure there are cases when mutliple ID vars are justified.

For now, combine the ID var using egen, see http://www.stata.com/help.cgi?egen. Like this:
`egen  new_ID_var = group(old_ID_vars) `

That will give you a unique ID but it if you wan to build the ID yourself you can concatenate like this:
`gen new_ID_var = old_ID_var1 + "_" + old_ID_var2`

To use the second example your ID vars need to be strings if they are numeric.

I will close this issue when I have implemented a fix to this.

**Comment by morevba** [comment]
Awesome, thanks Kris

**Comment by kbjarkefur** [comment]
Resolved by commit 3b79783 to the develop branch.

While resolved, the command still only allows one var in idvar(). Instead the help file is now explicit about only one var is allowed in idvar(). The help file now also make suggestions on how to proceed with the match in the case where multiple ID vars exist.

**Comment by kbjarkefur** [comment]
@mrimal , can you please take a look at the changes done in commit 3b79783? Thanks

**Comment by mrimal** [comment]
Looked at it, and it looks fine!

**Comment by kbjarkefur** [comment]
Thanks! I will close this issue once this update is on the SSC server.

Thanks both!
