### ISSUE TITLE
`ieboilstart , adopath()`: document that schemes also needs to go in ado-folder

### ISSUE THREAD

**Issue by bbdaniels** [worldbank/ietoolkit#326]
Trying to use `adopath` option to manage `ado` folder causes schemes to fail, even when explicitly set.

```
global dir "/Users/bbdaniels/GitHub/covet-tb-india"
ieboilstart, v(16.1) adopath("${dir}/ado" , strict)

// Install ado-files

  ssc install iefieldkit

  net from https://github.com/bbdaniels/stata/raw/main/
    net install labelcollapse

// Graph scheming

  copy "https://github.com/graykimbrough/uncluttered-stata-graphs/raw/master/schemes/scheme-uncluttered.scheme" ///
    "${dir}/scheme-uncluttered.scheme" , replace

  sysdir set PERSONAL "${dir}/"
  set scheme uncluttered , perm
```

Results in:
```
.   set scheme uncluttered , perm
scheme uncluttered not found
r(111);
```

and:
```
.   tw ///
>   (lowess correct pre_correct) ///
>   (lowess checklist pre_correct) ///
>   (lowess correct pre_correct) ///
> 
(note: scheme uncluttered not found, using s2color)
```

The instructions for installing schemes specifically ask that Stata is restarted once the scheme is placed in `PERSONAL`, so `ieboilstart` seems to be overriding that somehow. The scheme works again immediately upon restart as long as `ieboilstart` is not run.

**Comment by kbjarkefur** [comment]
what happens if you copy it into `"${dir}/ado"`?

**Comment by bbdaniels** [comment]
That works! Good to know -- not a bug then, but it does break some existing external functionality. Probably worth noting in wiki, but doesn't require changes to code I think. Feel free to close if you are happy with that.

**Comment by kbjarkefur** [comment]
Great, I had not thought of this and was not sure it would work. Yeah, definitely needs to be documented, but it seems as if that should be enough.

**Comment by kbjarkefur** [comment]
should be moved to `repado` in https://github.com/dime-worldbank/repkit

**Comment by kbjarkefur** [comment]
@bbdaniels , I created this article for this case: https://github.com/dime-worldbank/repkit/blob/repado-schemes/src/vignettes/schemes-with-repado.md

Can you please read and let me know if you agree that this is the documentation required? I do not work much with schemes so your eyes would be helpful. Feel free to make edits directly to that branch.

> The instructions for installing schemes specifically ask that Stata is restarted once the scheme is placed in PERSONAL [...]

Do you have a link to those installation instructions? If so, could you please add it to the article where I mention that this is the recommended practice?

When you are done, just go ahead and merge the PR https://github.com/dime-worldbank/repkit/pull/7
