### ISSUE TITLE
iematch - variable labels for _match*

### ISSUE THREAD

**Issue by morevba** [worldbank/ietoolkit#33]
It would be great if there could be variable labels for the following variables that are generated once you run the iematch command: 
_matchResult
_matchID
-matchDiff
-matchCount

**Comment by kbjarkefur** [comment]
That is a very good point. It will be included in next update. 

I will close this issue when it has been included in next update.

**Comment by kbjarkefur** [comment]
Fixed as of commit db300ff. This will be included in next major update and I will close this issue when the update is included in the version on Stata's SSC server.
