### ISSUE TITLE
Add option for latex in iebaltab

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/ietoolkit#5]
This is on our list and will hopefully be included in next version of ietoolkit. If you have resources for your favorite standardized format for a balance table, then please post them below. There are many different schools on how tables should be formatted and deciding for one of them will be what takes us the most time to add an option for latex to iebaltab.

**Comment by kbjarkefur** [comment]
Check list of items we need to do:

Research and decide on Standardized Table Formats
- [ ] Ask Economists for preferences
- [ ] Reserch what style guides top papers like AER and QJE has as style guides
- [ ] Research what economists like Duflo, Banerjee, and McKenzie have used in resent papers
- [ ] Based on this research show them to some economists on the 4th floor and ask for opinions
- [ ] Decide for one format! 

Implementation
- [ ]  Explore if we think that the "Parallel" or the "Browse file" version is the best method of approach
- [ ]  Implement based on method of approach and table format selected
- [ ] Test implementation
- [ ] Update help file
- [ ] Merge to master and publish on SSC

**Comment by krikkan** [comment]
iebaltab is not prepared for implementation of latex. I.e. onerowN option implemented, and variation is now displayed below the mean instead of separate column.  @luizaandrade, delete your fork and create a new fork  of the `develop' branch from the most recent commit.

**Comment by kbjarkefur** [comment]
iebaltab is not prepared for implementation of latex. I.e. onerowN option implemented, and variation is now displayed below the mean instead of separate column. @luizaandrade, delete your fork and create a new fork of the `develop` branch from the most recent commit.

**Comment by kbjarkefur** [comment]
@luizaandrade , I created a new branch that you can work from, see `develop-iebaltab-latex`. I will keep working from the `develop` branch and while it is possible for both of us to work from the same branch, this will generate a less messy merge process.

**Comment by kbjarkefur** [comment]
Florence wanted us to add a row with number of clusters per group underneath the row with N if the cluster option is used. @luizaandrade , let's discuss in our meetng.

**Comment by kbjarkefur** [comment]
updates are merged to the master branch. I will close this issue when the latex update is on SSC. I will open a new issue for clusters as it ended up not being included in this update.
