### ISSUE TITLE
iebaltab: Wrapping text when long varlabels are used

### ISSUE THREAD

**Issue by mrimal** [worldbank/ietoolkit#78]
The command does not automatically wrap text when varlabels are especially long and exporting to table to LaTeX. This can be manually solved in LaTeX but there is no option which can do it through iebaltab. 

Thanks.

**Comment by kbjarkefur** [comment]
One thing that makes this more difficult is for each balance variable there are two rows of statistics, see green lines in the image below. So if a **rowlabel** is wrapped over two rows then it should spill over in the empty space below. See the blue area in for balance variable _Var A_ in the image below. 

Perhaps one solution to this van be that we always merge the two cells in the first column (see the red are for _Var C_ in the image below) and adjust the text top left. Then it will look the same as it already does when the **rowlabel** is not wrapped. And nothing has to be adjusted when wrapping a label.

One issue is if the **rowlabel** is so long that it requires three rows. It is not obvious to me how the two rows of statistics should be expanded to still make it look good when the **rowlabel** requires three or more rows.

![image](https://user-images.githubusercontent.com/15911801/27611172-25b1635e-5b5f-11e7-9d99-fa7d34f8408a.png)

**Comment by kbjarkefur** [comment]
Corrected some typos in my previous comment. This is not even discussion implementation yet. This is jsut talking about how we want the result to look

**Comment by luizaandrade** [comment]
see comment below

![image](https://user-images.githubusercontent.com/15252541/27644613-033a9ba4-5bf2-11e7-87fe-c2855578b130.png)

**Comment by kbjarkefur** [comment]
When a width of a row is limited to a width so short that a **rowlabel** extends to three rows (see blue area) then the two rows of statistics should occupy the first and the second of those three rows, and an empty row needs to be added in all columns with statistics (see top green area). 

When a **rowlabel** requires four rows (maybe not advisable but still possible) then the columns with statistics needs two extra row (see bottom green area). And **rowlabels** covering 5 rows require three empty rows etc. 

Implementing this after knowing how many rows each **rowlabel** requires is fairly easy, but it is easier said than done to figure our how many rows are needed. 

Also, when **rowlabels** cover more than two rows the labels have no space in between then. Therefore we want to add some spacing in between each balance variable regardless if the **rowlabel** is wrapped or not (see red area). This makes it easier to read the statistics as well. The row spacing should perhaps be smaller than in the picture.

**Comment by kbjarkefur** [comment]
Also, we are currently thinking of an option **rowlabellatexcolumnwidth()** (lets think of a better name later) where you specify the width of the **rowlabel** column in centimeters. The rest, wrapping and adding or empty rows in the other columns should be implemented to be done automatically by command

**Comment by luizaandrade** [comment]
Solution pushed to develop branch in commits edba903, a119cc7 and 2ab8a77.

**Comment by kbjarkefur** [comment]
Thank you @luizaandrade ! I made a two small additions to your fix. 

Thank you both of you for not being frustrated (at least not showing it) when I kept being picky. But I really like the current solution! Yay!

I will close this issue when the update is on SSC.

**Comment by luizaandrade** [comment]
I'm glad you did, @kbjarkefur, it looks really good. I still have to update the help file.

Also, I was thinking maybe we should display the one N row after a horizontal line, as the F-test?
