### ISSUE TITLE
iebaltab : file path in save() cannot have a . in the name

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/ietoolkit#79]
When we are testing which file extension that is used in the **save()** option we are looking for the dot and compare the rest of the string to the file extensions allowed. However, it is possible to have a . in a folder name or anything meaning that there will be a . in the middle of the file path in **save()**. Then we are not comparing the file extension but a large part of the file path to the allowed file extensions and we will always get an error.

Does this apply to **savetex()** as well?

This problem should also be the case in commands with similar code, for example **iegraph**.

**Comment by kbjarkefur** [comment]
Solution for iebaltab for both **save()** and **savetex()** options. 

@mrimal , can you please update **iegraph** which I am quite sure have the same issue. Can you also please check the other commands if they have similar issues? **ieduplicates** could have that issue. Thanks!

**Comment by mrimal** [comment]
Solution pushed to develop branch in  commit  0aac531.

**Comment by kbjarkefur** [comment]
will close when update is available on SSC
