### ISSUE TITLE
iegraph :  yzero() does not work if the bars are negative

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/ietoolkit#82]
In a regression on a variable where the mean (for control) and the mean+beta (for treatment arms) are negative **yzero()** creates an error.  **yzero()** looks for the maximum value to determine the length of the axis but that is only correct for positive bars. Negative bars should use the minimum value.

This is most likely easily solved with an if-statement based on a test if the values for the bars are positive or negative. The only special case is when some bars are positive and some are negative. But in that case **yzero()** does not make sense as the 0 on the y-axis is included anyways.

So the solution to this issue is that if **yzero()** is used, then we should test that the value for all bars (and confidence intervals if used) are all positive or negative. If they are *not* then throw an error saying that the options cannot be used. If error is not thrown, then test if they are all positive and use maximum, otherwise use minimum.

**Comment by kbjarkefur** [comment]
@mrimal do you have time to look at this before Friday? You know this command better than anyone of us

**Comment by kbjarkefur** [comment]
Actually, instead of throwing an error when some values are positive and some are negative, we should maybe only throw a warning saying that the option **yzero()** should be ignored. What do you @mrimal and @luizaandrade think is better?

**Comment by luizaandrade** [comment]
Yes, I think just saying that the option was ignored is more efficient.

**Comment by kbjarkefur** [comment]
Solved. Will close when on SSC
