### ISSUE TITLE
iegitaddtxt : test new command

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/ietoolkit#94]
Please find _iegitaddtxt.ado_ in the `develop-iegitaddtxt` branch. See  _iegitaddtxt.sthlp_ in the same branch for the helpfile.

@mrimal please test this command for bugs and errors

@luizaandrade or anyone else, feel free to test it you too if you have some time to spare!

Report any bugs by writing to the branch (or create a pull request) or by commenting in this thread and I will fix.

**Comment by kbjarkefur** [comment]
We should test this on other operative systems. If it only works on Windows then our help file should stata that.

@mrimal , do you have a Stata license for your Linux machine?

Who can test this on a Mac?

**Comment by luizaandrade** [comment]
Exciting!!

**Comment by kbjarkefur** [comment]
The issue this command solves is explained [here](http://bytefreaks.net/gnulinux/bash/how-to-add-automatically-all-empty-folders-in-git-repository). The command is a Stata adaptation of the solution in that post.

**Comment by mrimal** [comment]
Tested the command and read the helpfile! Command works and helpfile is helpful!

**Comment by mrimal** [comment]
@kbjarkefur  Also, no license for Stata on my linux machine. As long as it works on a Mac, it should work on Ubuntu.
