### ISSUE TITLE
iefolder : put root file path in global_setup.do

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/ietoolkit#97]
In projects with many rounds there are many places where all users have to specify their root folder path.

By handling root folders in the global_setup.do file and calling that file in each master do file, it will limit the places this have to be specified to one, and it won't conflict with the preference that lead to issue #80

**Comment by kbjarkefur** [comment]
This cannot be done. In order to call the global_setup.do we need to have set up the root folder already. 

So we cannot define the root in a file that is meant to  be called from another file where the root is not defined as there is no way to access that file at that point. 

The root path needs to remain in the the master do-files.

**Comment by kbjarkefur** [comment]
I will keep this issue open for a while if anyone has any comments or reasons for not closing it. I will close this issue during next update to SSC.

Any comments for the reason to not fix this? @eatorange, @bbdaniels, @mrimal, @luizaandrade?

**Comment by gbedoyaWB** [comment]
I'm not sure I understand this issue, so don't feel qualified to respond. 
Min has established a path structure in the master do file that we only need to update once and run before working so that minimizes the changes in paths. Is this related to this?

**Comment by eatorange** [comment]
> In projects with many rounds there are many places where all users have to specify their root folder path.

I am not sure about this. No matter how many different rounds and how many different do-files we have, users don't need to specify their roots folders in each of those do-files as we generally use global macro for directories. Instead, we can specify all directory macros (root folder & sub-folders) in only one do-file so other do-files can simply use the macros declared from that do-file. (We would need to have directory macros in each do-files if we want our sub master do-files to be standalone, but do we want it?) 

We can include root paths either in global_setup.do file only or in project master do-file only and run it manually before running any other do-files including sub master do-files. If there's any change in root paths, we can simply change that do-file only.

Please let me know if you have any questions or comments.

**Comment by kbjarkefur** [comment]
I closed this issue without any fix. I will keep it as it was that the root folders are created in the project master do-file as well as the round master do-files. During the field coordinator training several people told me it was confusing they had to run one master do-file before running another. Teams that only want the root globals in the project master do-file can quite easily delete the root globals in the round master do-file if desired.

The reason we cannot have a the root globals in the global_setup.do is that in order for the master do-file to find the global_setup.do file it already needs to know the root folder, otherwise Stata will not find the file. So then the global_setup.do manually before running the master files, but that is very confusing and not very helpful.
