### ISSUE TITLE
ieboilstart: Typo in help file

### ISSUE THREAD

**Issue by eatorange** [worldbank/ietoolkit#99]
In "ieboilstart"'s help file, "custom" option refers to "example 4" as below,

_custom(string) allows the user to add one or multiple custom lines of code. Each line of code should be seperated with a "@". See example 4 below for more details._

However, there's no example 4 in the help file. I believe it should be example 2, which shows an example of "custom" option as below.

```
ieboilstart, versionnumber(12.1) custom(ssc install estout @ ssc install winsor)
`r(version)'
```

**Comment by kbjarkefur** [comment]
Thanks @eatorange ! You are right and I have fixed it in the `develop` branch. I will close this comment once the fix is updated on SSC. (Although we will wait for more major updates before sending an update.)
